name: WoW Price Monitor

on:
  schedule:
    # Se ejecuta automáticamente al minuto 0 de cada hora
    - cron: '0 * * * *'
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot de precios
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
